{
 "title": "EventStore",
 "description": "A dashboard for metrics exported with eventstore_exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "subject",
    "label": "Node",
    "query": "label_values(eventstore_up, subject)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "eventstore_up{subject=\"$subject\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "eventstore_cluster_member_is_clone{subject=\"$subject\"}*10+eventstore_cluster_member_is_master{subject=\"$subject\"}*1"
    }
   ]
  },
  {
   "title": "Cluster status",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "eventstore_cluster_member_alive{subject=\"$subject\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "eventstore_process_memory_bytes{subject=\"$subject\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "eventstore_process_cpu_scaled{subject=\"$subject\"}"
    }
   ]
  },
  { "title": "Projections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Projection status",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "eventstore_projection_running{subject=\"$subject\"}"
    }
   ]
  },
  {
   "title": "Projection progress",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "eventstore_projection_progress{subject=\"$subject\"}",
     "legendFormat": "{{projection}}"
    }
   ]
  },
  {
   "title": "Projection events per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eventstore_projection_events_processed_after_restart_total{subject=\"$subject\"}[5m])",
     "legendFormat": "{{projection}}"
    }
   ]
  },
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Subscription items rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(eventstore_subscription_items_processed_total[2m])",
     "legendFormat": "{{event_stream_id}}  -> {{group_name}}"
    }
   ]
  },
  {
   "title": "Subscription lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eventstore_subscription_last_known_event_number - eventstore_subscription_last_processed_event_number",
     "legendFormat": "{{event_stream_id}} -> {{group_name}}"
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Read / write ops per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(eventstore_disk_io_read_ops{subject=\"$subject\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(eventstore_disk_io_write_ops{subject=\"$subject\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "Read / written bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(eventstore_disk_io_read_bytes{subject=\"$subject\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "irate(eventstore_disk_io_written_bytes{subject=\"$subject\"}[1m])",
     "legendFormat": "written"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "TCP connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eventstore_tcp_connections{subject=\"$subject\"}"
    }
   ]
  },
  {
   "title": "Received / sent bytes per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "irate(eventstore_tcp_received_bytes{subject=\"$subject\"}[1m])",
     "legendFormat": "received"
    },
    {
     "expr": "irate(eventstore_tcp_sent_bytes{subject=\"$subject\"}[1m])",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}